/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsGocartRouteImport } from './routes/projects.gocart'
import { Route as ProjectsAdventureExplorerRouteImport } from './routes/projects.adventure-explorer'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsGocartRoute = ProjectsGocartRouteImport.update({
  id: '/projects/gocart',
  path: '/projects/gocart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAdventureExplorerRoute =
  ProjectsAdventureExplorerRouteImport.update({
    id: '/projects/adventure-explorer',
    path: '/projects/adventure-explorer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/adventure-explorer': typeof ProjectsAdventureExplorerRoute
  '/projects/gocart': typeof ProjectsGocartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/adventure-explorer': typeof ProjectsAdventureExplorerRoute
  '/projects/gocart': typeof ProjectsGocartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/adventure-explorer': typeof ProjectsAdventureExplorerRoute
  '/projects/gocart': typeof ProjectsGocartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/sitemap.xml'
    | '/projects/adventure-explorer'
    | '/projects/gocart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/sitemap.xml'
    | '/projects/adventure-explorer'
    | '/projects/gocart'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/sitemap.xml'
    | '/projects/adventure-explorer'
    | '/projects/gocart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsAdventureExplorerRoute: typeof ProjectsAdventureExplorerRoute
  ProjectsGocartRoute: typeof ProjectsGocartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/gocart': {
      id: '/projects/gocart'
      path: '/projects/gocart'
      fullPath: '/projects/gocart'
      preLoaderRoute: typeof ProjectsGocartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/adventure-explorer': {
      id: '/projects/adventure-explorer'
      path: '/projects/adventure-explorer'
      fullPath: '/projects/adventure-explorer'
      preLoaderRoute: typeof ProjectsAdventureExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsAdventureExplorerRoute: ProjectsAdventureExplorerRoute,
  ProjectsGocartRoute: ProjectsGocartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
