/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRollingPandaRouteImport } from './routes/projects.rolling-panda'
import { Route as ProjectsCandidClicksRouteImport } from './routes/projects.candid-clicks'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRollingPandaRoute = ProjectsRollingPandaRouteImport.update({
  id: '/projects/rolling-panda',
  path: '/projects/rolling-panda',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCandidClicksRoute = ProjectsCandidClicksRouteImport.update({
  id: '/projects/candid-clicks',
  path: '/projects/candid-clicks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/candid-clicks': typeof ProjectsCandidClicksRoute
  '/projects/rolling-panda': typeof ProjectsRollingPandaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/candid-clicks': typeof ProjectsCandidClicksRoute
  '/projects/rolling-panda': typeof ProjectsRollingPandaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/candid-clicks': typeof ProjectsCandidClicksRoute
  '/projects/rolling-panda': typeof ProjectsRollingPandaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/sitemap.xml'
    | '/projects/candid-clicks'
    | '/projects/rolling-panda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/sitemap.xml'
    | '/projects/candid-clicks'
    | '/projects/rolling-panda'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/sitemap.xml'
    | '/projects/candid-clicks'
    | '/projects/rolling-panda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsCandidClicksRoute: typeof ProjectsCandidClicksRoute
  ProjectsRollingPandaRoute: typeof ProjectsRollingPandaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/rolling-panda': {
      id: '/projects/rolling-panda'
      path: '/projects/rolling-panda'
      fullPath: '/projects/rolling-panda'
      preLoaderRoute: typeof ProjectsRollingPandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/candid-clicks': {
      id: '/projects/candid-clicks'
      path: '/projects/candid-clicks'
      fullPath: '/projects/candid-clicks'
      preLoaderRoute: typeof ProjectsCandidClicksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsCandidClicksRoute: ProjectsCandidClicksRoute,
  ProjectsRollingPandaRoute: ProjectsRollingPandaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
